import { Article, Author, MagazineEdition, Video, NavItem } from "./types";

export const authors: Author[] = [
  {
    id: "1",
    name: "Taushif Patel",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    role: "Co-Founder & Editor-in-Chief",
  },
  {
    id: "2",
    name: "Sunil Pandey",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
    role: "Co-Founder & Managing Editor",
  },
  {
    id: "3",
    name: "Priya Sharma",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    role: "Entertainment Editor",
  },
  {
    id: "4",
    name: "Rahul Verma",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
    role: "Sports Correspondent",
  },
  {
    id: "5",
    name: "Ananya Desai",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    role: "Tech & Lifestyle Writer",
  },
];

export const articles: Article[] = [
  // Featured/Breaking News
  {
    id: "1",
    slug: "india-space-mission-chandrayaan-4-launch-2025",
    title: "India Announces Chandrayaan-4 Mission: New Era of Lunar Exploration",
    excerpt: "ISRO reveals ambitious plans for the next lunar mission, aiming to bring back moon samples to Earth. The mission marks India's continued leadership in space exploration.",
    content: "India's space agency ISRO has announced the Chandrayaan-4 mission...",
    category: "technology",
    image: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1200&h=800&fit=crop",
    author: authors[0],
    publishedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    readingTime: 5,
    views: 125000,
    isFeatured: true,
    isBreaking: true,
    tags: ["ISRO", "Space", "Chandrayaan", "Moon Mission"],
  },
  {
    id: "2",
    slug: "bollywood-blockbuster-breaks-records-worldwide",
    title: "Pathaan 2 Shatters Box Office Records: Rs 500 Crore in Opening Weekend",
    excerpt: "Shah Rukh Khan's action spectacle becomes the fastest Indian film to cross the half-billion mark, rewriting Bollywood history.",
    content: "The much-anticipated sequel to Pathaan has taken the box office by storm...",
    category: "entertainment",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200&h=800&fit=crop",
    author: authors[2],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    readingTime: 4,
    views: 89000,
    isFeatured: true,
    isBreaking: false,
    tags: ["Bollywood", "SRK", "Box Office", "Movies"],
  },
  {
    id: "3",
    slug: "team-india-cricket-world-cup-triumph",
    title: "India Clinches Cricket World Cup 2025: A Historic Victory at Home",
    excerpt: "In an electrifying final at the Narendra Modi Stadium, Team India lifts the trophy after a decade-long wait, sending millions into celebration.",
    content: "Cricket history was made today as India emerged victorious...",
    category: "sports",
    image: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=1200&h=800&fit=crop",
    author: authors[3],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    readingTime: 6,
    views: 450000,
    isFeatured: true,
    isBreaking: true,
    tags: ["Cricket", "World Cup", "Team India", "Sports"],
  },
  // Technology
  {
    id: "4",
    slug: "ai-revolution-india-tech-industry-2025",
    title: "AI Startups in India Raise Record $5 Billion in 2025",
    excerpt: "The Indian AI ecosystem witnesses unprecedented growth as global investors bet big on homegrown innovation.",
    content: "India's artificial intelligence sector has emerged as a global powerhouse...",
    category: "technology",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200&h=800&fit=crop",
    author: authors[4],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    readingTime: 5,
    views: 34000,
    isFeatured: false,
    isBreaking: false,
    tags: ["AI", "Startups", "Technology", "Investment"],
  },
  {
    id: "5",
    slug: "5g-rollout-completes-india-digital-transformation",
    title: "India Completes Nationwide 5G Rollout: 700 Million Users Connected",
    excerpt: "A landmark achievement as India becomes the second-largest 5G market globally, transforming digital connectivity.",
    content: "The telecommunications revolution in India has reached a new milestone...",
    category: "technology",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&h=800&fit=crop",
    author: authors[0],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    readingTime: 4,
    views: 28000,
    isFeatured: false,
    isBreaking: false,
    tags: ["5G", "Telecom", "Digital India", "Technology"],
  },
  // Entertainment
  {
    id: "6",
    slug: "ott-platform-launches-biggest-series-2025",
    title: "Netflix India Announces Epic Historical Drama: 'Empire of the Mughals'",
    excerpt: "The streaming giant unveils its most ambitious Indian production with a star-studded cast and Rs 300 crore budget.",
    content: "Netflix India has announced what promises to be the most expensive...",
    category: "entertainment",
    image: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=1200&h=800&fit=crop",
    author: authors[2],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
    readingTime: 3,
    views: 56000,
    isFeatured: false,
    isBreaking: false,
    tags: ["Netflix", "OTT", "Series", "Entertainment"],
  },
  {
    id: "7",
    slug: "music-awards-2025-winners-ceremony-highlights",
    title: "Arijit Singh Wins 10th Filmfare Award: 'Music is My Life'",
    excerpt: "The legendary playback singer adds another trophy to his collection at the 70th Filmfare Awards ceremony in Mumbai.",
    content: "In a night filled with spectacular performances and emotional moments...",
    category: "entertainment",
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&h=800&fit=crop",
    author: authors[2],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    readingTime: 4,
    views: 78000,
    isFeatured: false,
    isBreaking: false,
    tags: ["Music", "Awards", "Bollywood", "Arijit Singh"],
  },
  // Sports
  {
    id: "8",
    slug: "ipl-2025-auction-record-breaking-bids",
    title: "IPL 2025 Auction: Young Pacer Fetches Record Rs 25 Crore Bid",
    excerpt: "The auction shatters all previous records as franchises engage in fierce bidding wars for emerging talent.",
    content: "The Indian Premier League auction lived up to its reputation...",
    category: "sports",
    image: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=1200&h=800&fit=crop",
    author: authors[3],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(),
    readingTime: 5,
    views: 92000,
    isFeatured: false,
    isBreaking: false,
    tags: ["IPL", "Cricket", "Auction", "Sports"],
  },
  {
    id: "9",
    slug: "indian-football-team-asian-games-gold",
    title: "Historic Gold: Indian Football Team Triumphs at Asian Games",
    excerpt: "After 62 years, India reclaims football glory with a stunning victory against South Korea in the final.",
    content: "Indian football has witnessed its greatest moment in six decades...",
    category: "sports",
    image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1200&h=800&fit=crop",
    author: authors[3],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 16).toISOString(),
    readingTime: 4,
    views: 67000,
    isFeatured: false,
    isBreaking: false,
    tags: ["Football", "Asian Games", "Team India", "Sports"],
  },
  // Travel
  {
    id: "10",
    slug: "kerala-tourism-record-visitors-2025",
    title: "Kerala Tourism Hits All-Time High: 20 Million Visitors in 2025",
    excerpt: "God's Own Country witnesses unprecedented tourist influx as sustainable tourism initiatives pay off.",
    content: "Kerala has set a new benchmark in Indian tourism...",
    category: "travel",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200&h=800&fit=crop",
    author: authors[4],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    readingTime: 5,
    views: 43000,
    isFeatured: false,
    isBreaking: false,
    tags: ["Kerala", "Tourism", "Travel", "India"],
  },
  {
    id: "11",
    slug: "new-vande-bharat-routes-himalayan-circuit",
    title: "Vande Bharat Express Connects Himalayan Circuit: A Game Changer",
    excerpt: "The new high-speed rail routes open up unprecedented access to North India's most scenic destinations.",
    content: "Indian Railways has launched a series of new Vande Bharat routes...",
    category: "travel",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&h=800&fit=crop",
    author: authors[1],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    readingTime: 4,
    views: 38000,
    isFeatured: false,
    isBreaking: false,
    tags: ["Railways", "Vande Bharat", "Travel", "Himalayas"],
  },
  // Lifestyle
  {
    id: "12",
    slug: "wellness-industry-india-growth-2025",
    title: "India's Wellness Industry Crosses $30 Billion Mark",
    excerpt: "From yoga retreats to Ayurveda spas, the wellness sector emerges as a major economic driver.",
    content: "The Indian wellness industry has achieved remarkable growth...",
    category: "lifestyle",
    image: "https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=1200&h=800&fit=crop",
    author: authors[4],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
    readingTime: 4,
    views: 29000,
    isFeatured: false,
    isBreaking: false,
    tags: ["Wellness", "Lifestyle", "Yoga", "Ayurveda"],
  },
  {
    id: "13",
    slug: "sustainable-living-trends-urban-india",
    title: "Green Living Revolution: Urban Indians Embrace Sustainability",
    excerpt: "From rooftop gardens to zero-waste shops, eco-conscious living becomes mainstream in metro cities.",
    content: "A green revolution is sweeping across urban India...",
    category: "lifestyle",
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=1200&h=800&fit=crop",
    author: authors[4],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    readingTime: 5,
    views: 21000,
    isFeatured: false,
    isBreaking: false,
    tags: ["Sustainability", "Lifestyle", "Green Living", "Urban"],
  },
  // Health
  {
    id: "14",
    slug: "india-universal-healthcare-milestone",
    title: "India's Ayushman Bharat Covers 500 Million Citizens",
    excerpt: "The world's largest healthcare program achieves a historic milestone, transforming medical access for millions.",
    content: "India's flagship healthcare initiative has reached an unprecedented scale...",
    category: "health",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200&h=800&fit=crop",
    author: authors[1],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    readingTime: 5,
    views: 54000,
    isFeatured: false,
    isBreaking: false,
    tags: ["Healthcare", "Ayushman Bharat", "Health", "Government"],
  },
  {
    id: "15",
    slug: "mental-health-awareness-campaign-india",
    title: "Breaking the Stigma: India's Mental Health Revolution",
    excerpt: "A nationwide campaign is transforming attitudes towards mental health, with record numbers seeking professional help.",
    content: "Mental health awareness in India has reached a turning point...",
    category: "health",
    image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=1200&h=800&fit=crop",
    author: authors[4],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    readingTime: 4,
    views: 36000,
    isFeatured: false,
    isBreaking: false,
    tags: ["Mental Health", "Wellness", "Health", "Awareness"],
  },
  // Fashion
  {
    id: "16",
    slug: "india-fashion-week-2025-highlights",
    title: "India Fashion Week 2025: Sustainable Couture Takes Center Stage",
    excerpt: "Leading designers showcase eco-friendly collections, signaling a paradigm shift in Indian fashion industry.",
    content: "The Lakme Fashion Week 2025 was a celebration of sustainable fashion...",
    category: "fashion",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=800&fit=crop",
    author: authors[2],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    readingTime: 4,
    views: 47000,
    isFeatured: false,
    isBreaking: false,
    tags: ["Fashion Week", "Fashion", "Sustainable", "Design"],
  },
  {
    id: "17",
    slug: "indian-designers-global-recognition",
    title: "Sabyasachi Collaborates with Gucci: Indian Design Goes Global",
    excerpt: "The iconic designer's partnership with the Italian luxury house marks a historic moment for Indian fashion.",
    content: "In a groundbreaking collaboration that bridges East and West...",
    category: "fashion",
    image: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=1200&h=800&fit=crop",
    author: authors[2],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 32).toISOString(),
    readingTime: 3,
    views: 62000,
    isFeatured: false,
    isBreaking: false,
    tags: ["Sabyasachi", "Gucci", "Fashion", "Luxury"],
  },
  // News
  {
    id: "18",
    slug: "india-economy-gdp-growth-2025",
    title: "India Becomes World's Third Largest Economy: Historic Achievement",
    excerpt: "Overtaking Japan and Germany, India cements its position as a global economic powerhouse.",
    content: "India has achieved a historic economic milestone...",
    category: "news",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200&h=800&fit=crop",
    author: authors[0],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 34).toISOString(),
    readingTime: 6,
    views: 187000,
    isFeatured: false,
    isBreaking: false,
    tags: ["Economy", "GDP", "India", "World News"],
  },
  {
    id: "19",
    slug: "education-reform-new-national-policy",
    title: "NEP 2.0: Major Reforms to Transform Indian Education",
    excerpt: "The updated National Education Policy introduces revolutionary changes to the schooling system.",
    content: "The Government of India has unveiled NEP 2.0...",
    category: "news",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200&h=800&fit=crop",
    author: authors[1],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    readingTime: 5,
    views: 73000,
    isFeatured: false,
    isBreaking: false,
    tags: ["Education", "NEP", "Policy", "Government"],
  },
  {
    id: "20",
    slug: "renewable-energy-india-solar-milestone",
    title: "India Surpasses 200 GW Renewable Energy Capacity",
    excerpt: "A green energy milestone as India leads the global transition towards sustainable power generation.",
    content: "India has achieved a landmark in renewable energy...",
    category: "news",
    image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1200&h=800&fit=crop",
    author: authors[0],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 38).toISOString(),
    readingTime: 4,
    views: 45000,
    isFeatured: false,
    isBreaking: false,
    tags: ["Renewable Energy", "Solar", "Green Energy", "Environment"],
  },
];

export const breakingNewsItems = [
  "BREAKING: India wins Cricket World Cup 2025 in thrilling final",
  "URGENT: Stock markets hit all-time high as GDP crosses $4 trillion",
  "ALERT: Chandrayaan-4 launch scheduled for next month",
  "TRENDING: Bollywood's biggest film crosses Rs 500 crore worldwide",
];

export const navigationItems: NavItem[] = [
  { label: "Home", href: "/" },
  { label: "News", href: "/category/news" },
  { label: "Entertainment", href: "/category/entertainment" },
  { label: "Sports", href: "/category/sports" },
  { label: "Technology", href: "/category/technology" },
  { label: "Travel", href: "/category/travel" },
  { label: "Lifestyle", href: "/category/lifestyle" },
  { label: "Health", href: "/category/health" },
  { label: "Fashion", href: "/category/fashion" },
];

export const magazineEditions: MagazineEdition[] = [
  {
    id: "1",
    title: "Times Applaud - March 2025",
    cover: "https://images.unsplash.com/photo-1586339949916-3e9457bef6d3?w=400&h=550&fit=crop",
    month: "March",
    year: 2025,
    downloadUrl: "#",
  },
  {
    id: "2",
    title: "Times Applaud - February 2025",
    cover: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=400&h=550&fit=crop",
    month: "February",
    year: 2025,
    downloadUrl: "#",
  },
  {
    id: "3",
    title: "Times Applaud - January 2025",
    cover: "https://images.unsplash.com/photo-1495020689067-958852a7765e?w=400&h=550&fit=crop",
    month: "January",
    year: 2025,
    downloadUrl: "#",
  },
  {
    id: "4",
    title: "Times Applaud - December 2024",
    cover: "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=400&h=550&fit=crop",
    month: "December",
    year: 2024,
    downloadUrl: "#",
  },
];

export const videos: Video[] = [
  {
    id: "1",
    title: "Inspiring Leaders Season 2 - Grand Finale Highlights",
    thumbnail: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=640&h=360&fit=crop",
    duration: "12:45",
    views: 125000,
    youtubeId: "dQw4w9WgXcQ",
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "2",
    title: "Times Applaud Exclusive: Bollywood's Rising Stars",
    thumbnail: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=640&h=360&fit=crop",
    duration: "8:32",
    views: 89000,
    youtubeId: "dQw4w9WgXcQ",
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: "3",
    title: "Cricket World Cup 2025: Journey to Glory",
    thumbnail: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=640&h=360&fit=crop",
    duration: "15:20",
    views: 234000,
    youtubeId: "dQw4w9WgXcQ",
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
  },
  {
    id: "4",
    title: "India's Tech Revolution: Startup Success Stories",
    thumbnail: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=640&h=360&fit=crop",
    duration: "10:15",
    views: 67000,
    youtubeId: "dQw4w9WgXcQ",
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
  },
];

// Helper functions to get filtered data
export const getFeaturedArticles = () => articles.filter((a) => a.isFeatured);
export const getBreakingArticles = () => articles.filter((a) => a.isBreaking);
export const getTrendingArticles = () => [...articles].sort((a, b) => b.views - a.views).slice(0, 8);
export const getLatestArticles = (count: number = 10) => 
  [...articles].sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime()).slice(0, count);
export const getArticlesByCategory = (category: string) => articles.filter((a) => a.category === category);
