import { Article, Author } from "./types";

// Real authors from Times Applaud
export const realAuthors: Author[] = [
  {
    id: "1",
    name: "Nitin Bhatnagar",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
    role: "Senior Editor",
  },
  {
    id: "2",
    name: "Shubham",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
    role: "Sports Correspondent",
  },
  {
    id: "3",
    name: "Taushif Patel",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    role: "Co-Founder & Editor-in-Chief",
  },
];

// Real articles extracted from www.timesapplaud.com (March 2026)
export const realArticles: Article[] = [
  // ENTERTAINMENT
  {
    id: "e1",
    slug: "banita-sandhu-wedding-fashion-anamika-khanna",
    title: "Banita Sandhu Brings Edgy Glam To Wedding Fashion In Anamika Khanna Ensemble",
    excerpt: "Actress Banita Sandhu recently grabbed attention with her stylish appearance at one of the most talked-about weddings of the season.",
    content: "Full article content...",
    category: "fashion",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=800&fit=crop",
    author: realAuthors[0],
    publishedAt: new Date("2026-03-12").toISOString(),
    readingTime: 4,
    views: 15420,
    isFeatured: false,
    isBreaking: false,
    tags: ["Fashion", "Wedding", "Celebrity"],
  },
  {
    id: "e2",
    slug: "suhana-khan-anamika-khanna-arjun-wedding",
    title: "Ethereal Suhana Khan Turns Heads In Anamika Khanna Couture At Arjun Tendulkar Wedding",
    excerpt: "Suhana Khan dazzled in Anamika Khanna couture at Arjun Tendulkar's wedding celebrations.",
    content: "Full article content...",
    category: "fashion",
    image: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=1200&h=800&fit=crop",
    author: realAuthors[0],
    publishedAt: new Date("2026-03-11").toISOString(),
    readingTime: 3,
    views: 28930,
    isFeatured: false,
    isBreaking: false,
    tags: ["Fashion", "Celebrity", "Wedding"],
  },
  {
    id: "e3",
    slug: "alia-bhatt-womens-day-ranbir-daughter",
    title: "Raha & Ranbir's Women's Day Surprise Left Alia in Tears",
    excerpt: "On International Women's Day, Alia Bhatt received a handwritten card from her two-year-old daughter Raha.",
    content: "Full article content...",
    category: "entertainment",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200&h=800&fit=crop",
    author: realAuthors[1],
    publishedAt: new Date("2026-03-09").toISOString(),
    readingTime: 3,
    views: 42150,
    isFeatured: true,
    isBreaking: false,
    tags: ["Bollywood", "Celebrity", "Women's Day"],
  },
  {
    id: "e4",
    slug: "saif-ali-khan-actor-pay-gender",
    title: "Saif Ali Khan Says Actor Pay Should Match Box Office Pull, Not Gender",
    excerpt: "Veteran actor Saif Ali Khan shares his thoughts on pay parity in Bollywood.",
    content: "Full article content...",
    category: "entertainment",
    image: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=1200&h=800&fit=crop",
    author: realAuthors[1],
    publishedAt: new Date("2026-03-09").toISOString(),
    readingTime: 4,
    views: 31280,
    isFeatured: false,
    isBreaking: false,
    tags: ["Bollywood", "Opinion", "Industry"],
  },

  // SPORTS
  {
    id: "s1",
    slug: "hardik-pandya-mahieka-world-cup-glory",
    title: "'Since She Came Into My Life, I've Only Been Winning': Hardik Pandya on Mahieka After WC Glory",
    excerpt: "When the final wicket fell at the Narendra Modi Stadium and India sealed a historic 96-run win over New Zealand, Hardik Pandya had special words.",
    content: "Full article content...",
    category: "sports",
    image: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=1200&h=800&fit=crop",
    author: realAuthors[1],
    publishedAt: new Date("2026-03-09").toISOString(),
    readingTime: 5,
    views: 89450,
    isFeatured: true,
    isBreaking: false,
    tags: ["Cricket", "World Cup", "Team India"],
  },
  {
    id: "s2",
    slug: "india-win-third-t20-world-cup-new-zealand",
    title: "India Win Third T20 World Cup Title With Record 96-Run Demolition of New Zealand",
    excerpt: "India clinched their third T20 World Cup title in a dominant performance against New Zealand at home.",
    content: "Full article content...",
    category: "sports",
    image: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=1200&h=800&fit=crop",
    author: realAuthors[1],
    publishedAt: new Date("2026-03-09").toISOString(),
    readingTime: 6,
    views: 125600,
    isFeatured: true,
    isBreaking: true,
    tags: ["Cricket", "World Cup", "Victory"],
  },
  {
    id: "s3",
    slug: "india-beat-england-wankhede-bollywood",
    title: "India Beat England by 7 Runs: Bollywood Erupts at Wankhede Stadium",
    excerpt: "Bollywood celebrities celebrated India's thrilling victory over England at Wankhede Stadium.",
    content: "Full article content...",
    category: "sports",
    image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1200&h=800&fit=crop",
    author: realAuthors[1],
    publishedAt: new Date("2026-03-06").toISOString(),
    readingTime: 4,
    views: 67890,
    isFeatured: false,
    isBreaking: false,
    tags: ["Cricket", "Bollywood", "Wankhede"],
  },

  // LIFESTYLE
  {
    id: "l1",
    slug: "gen-z-women-redefining-success-marriage",
    title: "Gen Z Women In India Are Redefining Success And Marriage Isn't Their Priority Anymore",
    excerpt: "For many young women today, life is no longer defined by the traditional timeline of marriage, children and settling down.",
    content: "Full article content...",
    category: "lifestyle",
    image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=1200&h=800&fit=crop",
    author: realAuthors[0],
    publishedAt: new Date("2026-03-07").toISOString(),
    readingTime: 5,
    views: 34520,
    isFeatured: true,
    isBreaking: false,
    tags: ["Lifestyle", "Gen Z", "Women", "Society"],
  },
  {
    id: "l2",
    slug: "dating-apps-tired-indians-study",
    title: "Indians Are Tired Of Dating Apps, Says New Study, Here's Why",
    excerpt: "A new study reveals why Indians are growing tired of dating apps and what they're looking for instead.",
    content: "Full article content...",
    category: "lifestyle",
    image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=1200&h=800&fit=crop",
    author: realAuthors[0],
    publishedAt: new Date("2026-03-12").toISOString(),
    readingTime: 4,
    views: 28940,
    isFeatured: false,
    isBreaking: false,
    tags: ["Lifestyle", "Dating", "Relationships"],
  },
  {
    id: "l3",
    slug: "kritika-kamra-wedding-red-saree",
    title: "Kritika Kamra's Wedding Look: All About Her Elegant Red Saree As She Marries Gaurav Kapur",
    excerpt: "Television actress Kritika Kamra tied the knot with Gaurav Kapur in a stunning red saree.",
    content: "Full article content...",
    category: "lifestyle",
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=1200&h=800&fit=crop",
    author: realAuthors[0],
    publishedAt: new Date("2026-03-12").toISOString(),
    readingTime: 3,
    views: 41230,
    isFeatured: false,
    isBreaking: false,
    tags: ["Lifestyle", "Celebrity", "Wedding"],
  },
  {
    id: "l4",
    slug: "gym-10-everyday-habits-fit",
    title: "Too Busy For The Gym? These 10 Everyday Habits Can Keep You Surprisingly Fit",
    excerpt: "You don't need hours at the gym to stay fit. These simple daily habits can make a big difference.",
    content: "Full article content...",
    category: "lifestyle",
    image: "https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=1200&h=800&fit=crop",
    author: realAuthors[0],
    publishedAt: new Date("2026-03-05").toISOString(),
    readingTime: 6,
    views: 23450,
    isFeatured: false,
    isBreaking: false,
    tags: ["Lifestyle", "Fitness", "Health"],
  },

  // HEALTH
  {
    id: "h1",
    slug: "legs-warning-signs-kidney-disease",
    title: "Your Legs Could Be Warning You! 5 Hidden Signs Of Kidney Disease Many People Ignore",
    excerpt: "Kidney disease is becoming a major health concern around the world, yet many people remain unaware that they have it.",
    content: "Full article content...",
    category: "health",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200&h=800&fit=crop",
    author: realAuthors[0],
    publishedAt: new Date("2026-03-12").toISOString(),
    readingTime: 5,
    views: 52340,
    isFeatured: true,
    isBreaking: false,
    tags: ["Health", "Medical", "Wellness"],
  },
  {
    id: "h2",
    slug: "india-sleep-crisis-public-health",
    title: "India's Growing Sleep Crisis: Experts Say Poor Rest Is Turning Into A Public Health Threat",
    excerpt: "Sleep deprivation is becoming a serious public health issue in India, experts warn.",
    content: "Full article content...",
    category: "health",
    image: "https://images.unsplash.com/photo-1541781777631-fa9531908431?w=1200&h=800&fit=crop",
    author: realAuthors[0],
    publishedAt: new Date("2026-03-10").toISOString(),
    readingTime: 6,
    views: 38920,
    isFeatured: false,
    isBreaking: false,
    tags: ["Health", "Sleep", "Wellness"],
  },
  {
    id: "h3",
    slug: "pmk-foundation-womens-day-cancer",
    title: "PMK Foundation Celebrates Women's Day with Cancer Warriors at Oberoi Mall for a Powerful Social Cause",
    excerpt: "The PMK Foundation organized a special event to honor cancer survivors on Women's Day.",
    content: "Full article content...",
    category: "health",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=1200&h=800&fit=crop",
    author: realAuthors[0],
    publishedAt: new Date("2026-03-10").toISOString(),
    readingTime: 4,
    views: 19870,
    isFeatured: false,
    isBreaking: false,
    tags: ["Health", "Cancer", "Social Cause"],
  },

  // TRAVEL
  {
    id: "t1",
    slug: "little-iran-india-iranian-community",
    title: "'Little Iran' In India? Do You Know About This Unique Iranian Community With Centuries-Old Roots",
    excerpt: "Trade between India and Iran, historically known as Persia, dates back thousands of years. One community keeps this legacy alive.",
    content: "Full article content...",
    category: "travel",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200&h=800&fit=crop",
    author: realAuthors[0],
    publishedAt: new Date("2026-03-12").toISOString(),
    readingTime: 6,
    views: 27650,
    isFeatured: true,
    isBreaking: false,
    tags: ["Travel", "History", "Culture"],
  },
  {
    id: "t2",
    slug: "kashmir-valley-of-lakes",
    title: "Here Is Why Kashmir Is Called The 'Valley Of Lakes' & The Reason Will Leave You Speechless",
    excerpt: "Some places feel like they belong in a painting. The Kashmir Valley is one of them.",
    content: "Full article content...",
    category: "travel",
    image: "https://images.unsplash.com/photo-1595846519845-68e29f8a3be4?w=1200&h=800&fit=crop",
    author: realAuthors[0],
    publishedAt: new Date("2026-03-11").toISOString(),
    readingTime: 5,
    views: 31240,
    isFeatured: false,
    isBreaking: false,
    tags: ["Travel", "Kashmir", "Nature"],
  },
  {
    id: "t3",
    slug: "asansol-land-of-black-diamond",
    title: "Why Is This Indian City Called The 'Land Of Black Diamond'? The Reason Is Buried Underground",
    excerpt: "Some cities are known for beaches, some for palaces and some for what lies deep beneath their soil. Asansol is one such place.",
    content: "Full article content...",
    category: "travel",
    image: "https://images.unsplash.com/photo-1518182170546-0766ce6fec56?w=1200&h=800&fit=crop",
    author: realAuthors[0],
    publishedAt: new Date("2026-03-10").toISOString(),
    readingTime: 5,
    views: 18930,
    isFeatured: false,
    isBreaking: false,
    tags: ["Travel", "India", "History"],
  },
  {
    id: "t4",
    slug: "kolkata-jute-powerhouse",
    title: "This Indian City Became The World's Jute Powerhouse & Here's Why Everyone Knows Its Name",
    excerpt: "Few cities build an identity around a single industry, but Kolkata did exactly that with jute.",
    content: "Full article content...",
    category: "travel",
    image: "https://images.unsplash.com/photo-1565060169308-7e6362060307?w=1200&h=800&fit=crop",
    author: realAuthors[0],
    publishedAt: new Date("2026-03-09").toISOString(),
    readingTime: 5,
    views: 22140,
    isFeatured: false,
    isBreaking: false,
    tags: ["Travel", "Kolkata", "Industry"],
  },
  {
    id: "t5",
    slug: "safest-places-india-women-solo-travel",
    title: "5 Safest Places In India Where Women Can Travel Solo Without Worry",
    excerpt: "Solo travel among women has grown rapidly in recent years, but safety still remains one of the biggest concerns.",
    content: "Full article content...",
    category: "travel",
    image: "https://images.unsplash.com/photo-1527631746610-bca00a040d60?w=1200&h=800&fit=crop",
    author: realAuthors[0],
    publishedAt: new Date("2026-03-07").toISOString(),
    readingTime: 7,
    views: 45670,
    isFeatured: false,
    isBreaking: false,
    tags: ["Travel", "Women", "Safety", "India"],
  },

  // TECHNOLOGY
  {
    id: "tech1",
    slug: "wired-earphones-cool-bluetooth-comeback",
    title: "Why Are Wired Earphones Suddenly Cool Again, Even With Bluetooth All Around You?",
    excerpt: "Just when it seemed like wireless Bluetooth earphones would take over everywhere, wired earphones are quietly making a big comeback.",
    content: "Full article content...",
    category: "technology",
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=1200&h=800&fit=crop",
    author: realAuthors[0],
    publishedAt: new Date("2026-02-19").toISOString(),
    readingTime: 5,
    views: 38450,
    isFeatured: true,
    isBreaking: false,
    tags: ["Technology", "Audio", "Trends"],
  },

  // NEWS (Additional)
  {
    id: "n1",
    slug: "empty-nest-divorce-marriages-break",
    title: "Why Marriages Break After Kids Leave House? The Surprising Rise Of 'Empty Nest Divorce'",
    excerpt: "An increasing number of couples are choosing to part ways once their children have grown up and left home.",
    content: "Full article content...",
    category: "lifestyle",
    image: "https://images.unsplash.com/photo-1516589178581-a7870abd07c5?w=1200&h=800&fit=crop",
    author: realAuthors[0],
    publishedAt: new Date("2026-02-27").toISOString(),
    readingTime: 6,
    views: 29340,
    isFeatured: false,
    isBreaking: false,
    tags: ["Lifestyle", "Relationships", "Marriage"],
  },
];

// Helper functions
export const getRealArticlesByCategory = (category: string) => 
  realArticles.filter((a) => a.category === category);

export const getRealLatestArticles = (count: number = 10) => 
  [...realArticles].sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime()).slice(0, count);

export const getRealTrendingArticles = () => 
  [...realArticles].sort((a, b) => b.views - a.views).slice(0, 8);

export const getRealFeaturedArticles = () => 
  realArticles.filter((a) => a.isFeatured);
